### ISSUE TITLE
When would the code be released

### ISSUE THREAD

**Issue by LokiXun** [miccunifi/TAPE#1]
Hi, This work is so wonderful. I am interested in VHS video and try to restore my own VHS tapes. I am wondering when would the code and the pretrained model be released?

Thanks

**Comment by LorenzoAgnolucci** [comment]
Hi @LokiXun,

Thanks for your interest in our work!

The code and the pre-trained model will be released before January.

**Comment by LokiXun** [comment]
Got it. Thanks for reply!

**Comment by LorenzoAgnolucci** [comment]
Hi @LokiXun!

We just released the pretrained model and the code for inference on real-world videos. Give it a try on your videos and feel free to open a new issue if you have problems or further questions.
