### ISSUE TITLE
How can this be used in a gui interface like comfy ui?

### ISSUE THREAD

**Issue by evolutionaryman** [miccunifi/TAPE#10]
How can this be used in a gui interface like comfy ui? I am trying to route it through multiple models.

**Comment by LorenzoAgnolucci** [comment]
Hi @evolutionaryman,

I'm sorry but we are not planning to release a GUI. Also, I'm not familiar with Comfy UI so I don't know how to help you.

**Comment by evolutionaryman** [comment]
Thank you for the quick response.
