### ISSUE TITLE
Out of memory!

### ISSUE THREAD

**Issue by primepake** [miccunifi/TAPE#11]
I used the same config with your training but got OOM! Are you sure it's correct?

**Comment by LorenzoAgnolucci** [comment]
Hi! What GPU are you using?

**Comment by primepake** [comment]
I'm using H100 with 80GB

**Comment by LorenzoAgnolucci** [comment]
I see. Are you training the model with the default resolution?

**Comment by primepake** [comment]
yes 512x512? have you tried with accelerator? I trained with it and got OOM

**Comment by LorenzoAgnolucci** [comment]
By default, the `--train-patch-size` parameter is set to 128. I've never tried using accelerator, sorry.

**Comment by primepake** [comment]
tried to use your code but got issue!
![image](https://github.com/user-attachments/assets/db3521e8-c08b-40f4-a11b-a57906a0ac9b)

**Comment by primepake** [comment]
I just started the training but I'm checking your code, it only input with the shape 
imgs_lq.shape, imgs_gt.shape, imgs_ref.shape: torch.Size([2, 5, 3, 128, 128]) torch.Size([2, 5, 3, 128, 128]) torch.Size([2, 5, 3, 128, 128])
so why in the inference you run with 512 image?

**Comment by primepake** [comment]
can you share the chart of you loss values?
<img width="1614" alt="image" src="https://github.com/user-attachments/assets/36c2a65e-7a0f-427a-809c-bdc6da8d7f5f">

**Comment by LorenzoAgnolucci** [comment]
In image and video restoration, training with a patch size smaller than the test one is quite a common way to save memory during training. On which dataset are you training? Is it the one of the paper or a custom one?

**Comment by primepake** [comment]
I'm training with car dataset

**Comment by LorenzoAgnolucci** [comment]
Can I see a video example somewhere? Is it public?

**Comment by primepake** [comment]
yes! it recorded around the car
https://www.kaggle.com/datasets/tapakah68/videos-around-cars

**Comment by LorenzoAgnolucci** [comment]
What's the end goal of your work? Because the videos don't seem degraded with artifacts similar to those considered in our paper.

**Comment by primepake** [comment]
I want to increase the quality of the image by degradation ground truth image while training.

**Comment by LorenzoAgnolucci** [comment]
What kind of degradation? Our model is designed for analog video restoration, I'm not sure it's suitable for your purpose.

**Comment by primepake** [comment]
it's simple degradations (gaussian noise, blur gaussian, blur part of car, downsample_upsample) in video

**Comment by LorenzoAgnolucci** [comment]
How did you determine the reference frames? Did you use the standard textual prompts or did you change them to fit your needs?

By the way, I'm closing the issue since the out of memory problem is now solved.

**Comment by primepake** [comment]
I just select random from dataset. Do you if we select different views it will support that?

**Comment by LorenzoAgnolucci** [comment]
Why should random frames represent reference frames for the restoration? In the paper, we devised a specific methodology for analog videos. You should try to adjust that for your needs if you want to use our model for your purpose.

**Comment by primepake** [comment]
I'm just thinking while training we can select random then the model can learn better after that, in the inference stage we can choose reference based on CLIP score.

**Comment by LorenzoAgnolucci** [comment]
I've never tried it, so I'm not sure if it will work (or not)

**Comment by primepake** [comment]
Thanks! Can you provide your training chart?

**Comment by LorenzoAgnolucci** [comment]
I don't have the charts anymore, but I have the values of the losses at the end of the training: about 3.2 for the pixel_loss, and about 4.6 for the perceptual_loss. However, since you are using a different training dataset, I don't think these values are useful for you. But from what I remember, the profiles of the losses were similar to your charts.

**Comment by primepake** [comment]
Thanks a lot!
