### ISSUE TITLE
Creating our own custom synthetic datasets

### ISSUE THREAD

**Issue by AndroYD84** [miccunifi/TAPE#3]
Hello, would it be possible to share your Adobe After Effects project files (maybe containing a small video that we can replace with our own) or explain the step-by-step procedure how you made the synthetic artifacts? I'm interested in restoring some historical cartoon videos, so I need a different kind of synthetic dataset.

**Comment by LorenzoAgnolucci** [comment]
Hi @AndroYD84!

Sorry for the late answer and thank you for your interest in our work!

I will check if it is possible to share the Adobe After Effects project files and then I will update this issue ASAP. In the meantime, you can refer to the supplementary material of our paper for more details on how we generated the synthetic dataset.

**Comment by LorenzoAgnolucci** [comment]
Hi @AndroYD84!

I uploaded the Adobe After Effects files [here](https://drive.google.com/drive/folders/1eai8jrO4xsKz0NWiiAonvxhhGFRCVAky?usp=drive_link).
