### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by evolutionaryman** [miccunifi/TAPE#4]
Your research is really stunning. Thank you for aiming at analog video as this is an area that people forget exists. Are you and your team considering mixing your work with current methods of restore/upscaling in addition to the work of correcting analog errors/timing errors?   Examples of this would be the more recent "HAT: Hybrid Attention Transformer for Image Restoration" or BasicVSR++. There are in depth research methods available as well as code examples. 

HAT: https://github.com/xpixelgroup/hat
BasicVSR++ : https://ckkelvinchan.github.io/projects/BasicVSR++/

It could be used to restore more analog details once your method has finished grabbing what it can.

I can't wait to see what you all come up with next. Truly Exciting!
Thank you for sharing this with the world!

**Comment by LorenzoAgnolucci** [comment]
Hi @evolutionaryman!

Thanks for your interest in our work, I appreciate your kind words!

As of now, we are not planning to combine our approach with other video restoration methods. However, applying these methods on top of ours should be quite straightforward. Indeed, given degraded frames coming from a real-world video, you could start by using our model to remove the artifacts typical of analog videos. Then, you could apply e.g. BasicVSR++ to upscale the restored frames. I haven't tried this myself but I think it can work and is worth a try.

Feel free to ask further questions if you need assistance with this.

Lorenzo
