### ISSUE TITLE
Tried to run the script but getting this errors

### ISSUE THREAD

**Issue by ghost** [miccunifi/TAPE#5]
Hey there thanks for this, I'm trying to revive old videos from my grand mother, thanks for this!

I'm trying to run this script 
 
`C:\Users\StudioPC\Documents\TAPE\TAPE> python real_world_inference.py --input-path "C:\Users\StudioPC\Videos\JVC-VHSC" --output-path "C:\Users\StudioPC\Videos\JVC-VHSC\Output" `

at first try it started to classify images.

![image](https://github.com/miccunifi/TAPE/assets/22463926/1b97de33-773c-40f6-847c-5bca9fa6662f)

but then I'm getting this error

![image](https://github.com/miccunifi/TAPE/assets/22463926/3e3d472f-1295-44ae-b640-368566bd42cf)

Then I erased the output folder and tried again the first script and i got this 

![image](https://github.com/miccunifi/TAPE/assets/22463926/937c845a-e917-44db-9f82-07b5d06eac15)

all the videos on the Input folder are "mp4"

Am I missing some args? 

Thanks in advance!

**Comment by LorenzoAgnolucci** [comment]
Hi @paul-bg!

Thanks for your interest in our work!

The script takes in input the path of the input video and not of the input folder. Therefore, if you want to restore multiple videos, you need to run the script multiple times.
