### ISSUE TITLE
Error on restoring the video

### ISSUE THREAD

**Issue by ghost** [miccunifi/TAPE#6]
Im currently facing this issue 

![image](https://github.com/miccunifi/TAPE/assets/22463926/867387cb-788b-432b-abcd-bdf5e3eeb0d7)

I tried to run the script 2 times but I got the same error.

I have a RTX 3060ti 8gb  no other apps running at same time fully dedicated to this

**Comment by LorenzoAgnolucci** [comment]
Hi @paul-bg!

Try reducing the patch size to 256. Consider that, being a video restoration method, TAPE is quite resource-intensive and your GPU may simply not have enough memory.
